import { z } from "zod";

export type SettingType = "NUMBER" | "BOOLEAN" | "STRING";

export interface SettingDefinition {
  key: string;
  type: SettingType;
  category: string;
  label: string;
  description: string;
  default: string; // serialized default; interpreted per `type`
  min?: number; // NUMBER only — admin-side hint + server clamp
  max?: number;
  integer?: boolean; // NUMBER only — reject fractional values
  enum?: readonly string[]; // STRING only — allowed values
  /** Write-only credential: its value is never returned by the API; an empty
   *  submission means "keep the existing value". */
  secret?: boolean;
}

/**
 * The single source of truth for every configurable setting. The DB only
 * stores overrides; metadata + defaults live here so they version with code.
 * Modules read values through SettingsService typed getters.
 */
export const SETTINGS_REGISTRY: readonly SettingDefinition[] = [
  // --- Add Coins (Razorpay package) ---
  {
    key: "payment.razorpay.keyId",
    type: "STRING",
    category: "Add Coins",
    label: "Razorpay key ID",
    description:
      "Server-side key used by Add Coins and Ludo Razorpay flows. Falls back to environment variables when empty.",
    default: "",
  },
  {
    key: "payment.razorpay.keySecret",
    type: "STRING",
    category: "Add Coins",
    label: "Razorpay key secret",
    description: "Secret is never returned in responses. Leave blank to keep the existing value.",
    default: "",
    secret: true,
  },
  {
    key: "coinPurchase.enabled",
    type: "BOOLEAN",
    category: "Add Coins",
    label: "Add Coins enabled",
    description:
      "Show the Razorpay Add Coins flow. Razorpay server credentials must also be configured.",
    default: "false",
  },
  {
    key: "coinPurchase.packPriceRupees",
    type: "NUMBER",
    category: "Add Coins",
    label: "Package price (INR)",
    description: "Rupees charged for one coin package.",
    default: "10",
    min: 1,
    max: 100000,
    integer: true,
  },
  {
    key: "coinPurchase.coinsPerPack",
    type: "NUMBER",
    category: "Add Coins",
    label: "Coins per package",
    description: "Coins credited after one package payment is captured.",
    default: "100",
    min: 1,
    max: 100000000,
    integer: true,
  },
  {
    key: "coinPurchase.maxPacks",
    type: "NUMBER",
    category: "Add Coins",
    label: "Maximum packages per payment",
    description: "Largest package quantity a user may buy in one Razorpay payment.",
    default: "10",
    min: 1,
    max: 100,
    integer: true,
  },
  // --- Withdrawals (Module 6) ---
  {
    key: "withdrawal.enabled",
    type: "BOOLEAN",
    category: "Withdrawals",
    label: "Withdrawals enabled",
    description: "Master switch for the user withdrawal feature.",
    default: "true",
  },
  {
    key: "withdrawal.minAmount",
    type: "NUMBER",
    category: "Withdrawals",
    label: "Minimum withdrawal amount",
    description: "Smallest amount a user may request to withdraw.",
    default: "100",
    min: 1,
    max: 1_000_000,
  },
  // --- Redemptions (coins -> gift voucher) ---
  {
    key: "redeem.enabled",
    type: "BOOLEAN",
    category: "Redemptions",
    label: "Redemptions enabled",
    description: "Master switch for coin-redemption requests.",
    default: "true",
  },
  {
    key: "redeem.minCoins",
    type: "NUMBER",
    category: "Redemptions",
    label: "Minimum redemption coins",
    description: "Smallest number of coins a user may redeem in one request.",
    default: "100",
    min: 1,
    max: 1_000_000,
  },
  // --- UPI payouts (coins -> rupees paid to the user's UPI ID) ---
  {
    key: "redeem.upi.enabled",
    type: "BOOLEAN",
    category: "UPI Payouts",
    label: "UPI payouts enabled",
    description:
      "Master switch for redeeming coins as rupees paid to the user's UPI ID (settled manually from the admin panel).",
    default: "true",
  },
  {
    key: "redeem.upi.coinsPerRupee",
    type: "NUMBER",
    category: "UPI Payouts",
    label: "Coins per rupee",
    description: "Conversion rate: how many coins equal ₹1. Example: 10 means 100 coins = ₹10.",
    default: "10",
    min: 0.01,
    max: 1_000_000,
  },
  {
    key: "redeem.upi.minCoins",
    type: "NUMBER",
    category: "UPI Payouts",
    label: "Minimum UPI payout coins",
    description: "Smallest number of coins a user may redeem for a UPI payout in one request.",
    default: "100",
    min: 1,
    max: 1_000_000,
    integer: true,
  },
  // --- Reward provider: Xoxoday Plum (coins -> gift-card codes / reward links) ---
  {
    key: "xoxoday.enabled",
    type: "BOOLEAN",
    category: "Reward Providers",
    label: "Xoxoday enabled",
    description:
      "Master switch for auto-issuing Xoxoday vouchers on redemption approval. When off (or credentials missing), approved Xoxoday redemptions queue for manual fulfillment.",
    default: "true",
  },
  {
    key: "xoxoday.baseUrl",
    type: "STRING",
    category: "Reward Providers",
    label: "Xoxoday API base URL",
    description:
      "Plum OAuth API base, e.g. https://accounts.xoxoday.com/chef/v1/oauth (production) or the staging equivalent. Leave blank to use the server default.",
    default: "",
  },
  {
    key: "xoxoday.accessToken",
    type: "STRING",
    category: "Reward Providers",
    label: "Xoxoday access token",
    description: "OAuth access token. Presence of this token is what enables auto-issue.",
    default: "",
    secret: true,
  },
  {
    key: "xoxoday.refreshToken",
    type: "STRING",
    category: "Reward Providers",
    label: "Xoxoday refresh token",
    description:
      "OAuth refresh token (rotates on use). Needed with client id/secret so an expired access token can auto-refresh.",
    default: "",
    secret: true,
  },
  {
    key: "xoxoday.clientId",
    type: "STRING",
    category: "Reward Providers",
    label: "Xoxoday client ID",
    description: "OAuth client id used for the refresh-token flow.",
    default: "",
  },
  {
    key: "xoxoday.clientSecret",
    type: "STRING",
    category: "Reward Providers",
    label: "Xoxoday client secret",
    description: "OAuth client secret used for the refresh-token flow.",
    default: "",
    secret: true,
  },
  {
    key: "xoxoday.defaultProductId",
    type: "STRING",
    category: "Reward Providers",
    label: "Default gift-card product/SKU ID",
    description:
      "Fallback Plum product/SKU id used for gift-card-code vouchers when a catalog item doesn't set its own.",
    default: "",
  },
  {
    key: "xoxoday.defaultCampaignId",
    type: "STRING",
    category: "Reward Providers",
    label: "Default reward-link campaign ID",
    description:
      "Fallback Plum campaign id used for reward-link vouchers when a catalog item doesn't set its own.",
    default: "",
  },
  {
    key: "xoxoday.linkExpiryDays",
    type: "NUMBER",
    category: "Reward Providers",
    label: "Reward-link expiry (days)",
    description: "How long a generated Plum reward link stays claimable.",
    default: "90",
    min: 1,
    max: 3650,
  },
  // --- Referrals ---
  {
    key: "referral.rewardPoints",
    type: "NUMBER",
    category: "Referrals",
    label: "Referral reward points",
    description: "Points credited to the referrer when an invited user applies their code",
    default: "50",
    min: 0,
    max: 1_000_000,
  },
  // --- Fraud & duplicate protection (Module 4) ---
  {
    key: "fraud.rejectDuplicateImages",
    type: "BOOLEAN",
    category: "Fraud",
    label: "Reject duplicate screenshots",
    description: "Auto-reject a submission whose image hash matches a prior one.",
    default: "true",
  },
  {
    key: "fraud.flagScoreThreshold",
    type: "NUMBER",
    category: "Fraud",
    label: "Fraud score flag threshold",
    description: "Flag a user for review once their fraud score reaches this value.",
    default: "50",
    min: 1,
    max: 1000,
  },
  {
    key: "fraud.suspiciousPendingCount",
    type: "NUMBER",
    category: "Fraud",
    label: "Suspicious pending count",
    description: "Log a suspicious event when a user exceeds this many pending submissions.",
    default: "5",
    min: 1,
    max: 100,
  },
  // --- Submissions (Modules 3 & 4) ---
  {
    key: "submission.maxImageSizeMb",
    type: "NUMBER",
    category: "Submissions",
    label: "Max screenshot size (MB)",
    description: "Reject proof uploads larger than this.",
    default: "5",
    min: 1,
    max: 25,
  },
  {
    key: "submission.allowResubmitAfterReject",
    type: "BOOLEAN",
    category: "Submissions",
    label: "Allow resubmit after rejection",
    description: "Let users submit a fresh screenshot for an offer they were rejected on.",
    default: "true",
  },
  // --- Games (3-piece tic-tac-toe) ---
  {
    key: "game.ttt.enabled",
    type: "BOOLEAN",
    category: "Games",
    label: "Tic-tac-toe enabled",
    description: "Master switch for the 3-piece tic-tac-toe game.",
    default: "true",
  },
  {
    key: "game.ttt.winCoins",
    type: "NUMBER",
    category: "Games",
    label: "Tic-tac-toe win coins",
    description: "Coins credited when a user beats the AI.",
    default: "20",
    min: 0,
    max: 1_000_000,
  },
  {
    key: "game.ttt.difficulty",
    type: "STRING",
    category: "Games",
    label: "Tic-tac-toe AI difficulty",
    description: "AI strength: EASY, MEDIUM, HARD or IMPOSSIBLE.",
    default: "MEDIUM",
    enum: ["EASY", "MEDIUM", "HARD", "IMPOSSIBLE"],
  },
  {
    key: "game.ttt.hintWinCoins",
    type: "NUMBER",
    category: "Games",
    label: "Tic-tac-toe hinted-win coins",
    description: "Coins credited for a win when the removal hint was enabled.",
    default: "5",
    min: 0,
    max: 1_000_000,
  },
  {
    key: "game.ttt.freeDailyLimit",
    type: "NUMBER",
    category: "Games",
    label: "Free daily matches",
    description: "Daily Tic-tac-toe matches for users without a paid membership.",
    default: "3",
    min: 0,
    max: 1000,
    integer: true,
  },
  {
    key: "game.ttt.plusDailyLimit",
    type: "NUMBER",
    category: "Games",
    label: "Plus daily matches",
    description: "Daily Tic-tac-toe matches for active Plus members.",
    default: "10",
    min: 0,
    max: 1000,
    integer: true,
  },
  {
    key: "game.ttt.proDailyLimit",
    type: "NUMBER",
    category: "Games",
    label: "Pro daily matches",
    description: "Daily Tic-tac-toe matches for active Pro members.",
    default: "25",
    min: 0,
    max: 1000,
    integer: true,
  },
  // --- Roulette (virtual-coin roulette game) ---
  // General
  {
    key: "game.roulette.title",
    type: "STRING",
    category: "Roulette",
    label: "Game title",
    description: "Headline shown on the roulette game screen.",
    default: "Golden Roulette",
  },
  {
    key: "game.roulette.subtitle",
    type: "STRING",
    category: "Roulette",
    label: "Game subtitle",
    description: "Short tagline under the title.",
    default: "Play with virtual coins",
  },
  {
    key: "game.roulette.instructions",
    type: "STRING",
    category: "Roulette",
    label: "How-to-play text",
    description: "Rules text shown in the game's rules sheet.",
    default:
      "Pick a bet, choose your coins, and spin. Match the winning pocket to win. Coins are for entertainment only and have no cash value.",
  },
  {
    key: "game.roulette.enabled",
    type: "BOOLEAN",
    category: "Roulette",
    label: "Roulette enabled",
    description: "Master switch for the roulette game.",
    default: "true",
  },
  {
    key: "game.roulette.maintenanceMode",
    type: "BOOLEAN",
    category: "Roulette",
    label: "Maintenance mode",
    description: "When on, the game loads but play is blocked with a maintenance message.",
    default: "false",
  },
  {
    key: "game.roulette.minBet",
    type: "NUMBER",
    category: "Roulette",
    label: "Minimum bet (coins)",
    description: "Smallest wallet-coin stake allowed on a paid spin.",
    default: "10",
    min: 1,
    max: 1_000_000,
    integer: true,
  },
  {
    key: "game.roulette.maxBet",
    type: "NUMBER",
    category: "Roulette",
    label: "Maximum bet (coins)",
    description: "Largest wallet-coin stake allowed on a paid spin.",
    default: "1000",
    min: 1,
    max: 1_000_000,
    integer: true,
  },
  {
    key: "game.roulette.defaultBet",
    type: "NUMBER",
    category: "Roulette",
    label: "Default bet (coins)",
    description: "Pre-selected stake when the game opens.",
    default: "50",
    min: 1,
    max: 1_000_000,
    integer: true,
  },
  {
    key: "game.roulette.betStep",
    type: "NUMBER",
    category: "Roulette",
    label: "Bet increment (coins)",
    description: "Step used by the +/- stake controls.",
    default: "10",
    min: 1,
    max: 1_000_000,
    integer: true,
  },
  {
    key: "game.roulette.animationDurationMs",
    type: "NUMBER",
    category: "Roulette",
    label: "Wheel animation duration (ms)",
    description: "How long the wheel+ball animation runs before revealing the result.",
    default: "3500",
    min: 1000,
    max: 20000,
    integer: true,
  },
  {
    key: "game.roulette.resultModalMs",
    type: "NUMBER",
    category: "Roulette",
    label: "Result modal duration (ms)",
    description: "How long the win/loss result modal auto-displays.",
    default: "4000",
    min: 500,
    max: 20000,
    integer: true,
  },
  {
    key: "game.roulette.cooldownSeconds",
    type: "NUMBER",
    category: "Roulette",
    label: "Cooldown between spins (seconds)",
    description: "Minimum seconds between a user's spins (0 = no cooldown).",
    default: "0",
    min: 0,
    max: 3600,
    integer: true,
  },
  {
    key: "game.roulette.maxGamesPerDay",
    type: "NUMBER",
    category: "Roulette",
    label: "Max total spins per day",
    description: "Free + paid spins a user may play per day.",
    default: "100",
    min: 0,
    max: 100000,
    integer: true,
  },
  {
    key: "game.roulette.maxPaidGamesPerDay",
    type: "NUMBER",
    category: "Roulette",
    label: "Max paid spins per day",
    description: "Wallet-coin spins a user may play per day.",
    default: "100",
    min: 0,
    max: 100000,
    integer: true,
  },
  {
    key: "game.roulette.resetTimezone",
    type: "STRING",
    category: "Roulette",
    label: "Daily reset timezone",
    description: "IANA timezone whose midnight resets daily free games and limits.",
    default: "Asia/Kolkata",
  },
  {
    key: "game.roulette.soundEnabled",
    type: "BOOLEAN",
    category: "Roulette",
    label: "Sound enabled (default)",
    description: "Default sound state for the game (user can still mute locally).",
    default: "true",
  },
  {
    key: "game.roulette.hapticsEnabled",
    type: "BOOLEAN",
    category: "Roulette",
    label: "Haptics enabled (default)",
    description: "Default haptic/vibration feedback state on mobile.",
    default: "true",
  },
  // Free games
  {
    key: "game.roulette.freeGamesEnabled",
    type: "BOOLEAN",
    category: "Roulette",
    label: "Free games enabled",
    description: "Whether users get daily free spins that don't touch the wallet.",
    default: "true",
  },
  {
    key: "game.roulette.dailyFreeGames",
    type: "NUMBER",
    category: "Roulette",
    label: "Free spins per day",
    description: "Number of free spins each user gets per day.",
    default: "3",
    min: 0,
    max: 1000,
    integer: true,
  },
  {
    key: "game.roulette.freeGameStake",
    type: "NUMBER",
    category: "Roulette",
    label: "Free-spin stake value (coins)",
    description:
      "Notional stake a free spin plays with; wins pay against this, no coins are debited.",
    default: "50",
    min: 1,
    max: 1_000_000,
    integer: true,
  },
  // Payouts (profit "X to 1" multiplier; total credited on win = stake x (multiplier + 1))
  {
    key: "game.roulette.payout.number",
    type: "NUMBER",
    category: "Roulette",
    label: "Exact-number payout (to 1)",
    description: "Profit multiplier for a winning straight-up number bet (standard = 35).",
    default: "35",
    min: 0,
    max: 1000,
    integer: true,
  },
  {
    key: "game.roulette.payout.odd",
    type: "NUMBER",
    category: "Roulette",
    label: "Odd payout (to 1)",
    description: "Profit multiplier for a winning odd bet (standard = 1).",
    default: "1",
    min: 0,
    max: 1000,
    integer: true,
  },
  {
    key: "game.roulette.payout.even",
    type: "NUMBER",
    category: "Roulette",
    label: "Even payout (to 1)",
    description: "Profit multiplier for a winning even bet (standard = 1).",
    default: "1",
    min: 0,
    max: 1000,
    integer: true,
  },
  {
    key: "game.roulette.payout.red",
    type: "NUMBER",
    category: "Roulette",
    label: "Red payout (to 1)",
    description: "Profit multiplier for a winning red bet (standard = 1).",
    default: "1",
    min: 0,
    max: 1000,
    integer: true,
  },
  {
    key: "game.roulette.payout.black",
    type: "NUMBER",
    category: "Roulette",
    label: "Black payout (to 1)",
    description: "Profit multiplier for a winning black bet (standard = 1).",
    default: "1",
    min: 0,
    max: 1000,
    integer: true,
  },
  {
    key: "game.roulette.maxPayoutPerGame",
    type: "NUMBER",
    category: "Roulette",
    label: "Max payout per spin (coins)",
    description:
      "Reject a bet before spinning when its configured full win would exceed this amount.",
    default: "100000",
    min: 0,
    max: 100_000_000,
    integer: true,
  },
  {
    key: "game.roulette.maxPayoutPerUserPerDay",
    type: "NUMBER",
    category: "Roulette",
    label: "Max payout per user per day (coins)",
    description:
      "Reject a bet before spinning when its configured full win exceeds the user's remaining daily allowance.",
    default: "500000",
    min: 0,
    max: 100_000_000,
    integer: true,
  },
  // Bet-type switches
  {
    key: "game.roulette.bet.numberEnabled",
    type: "BOOLEAN",
    category: "Roulette",
    label: "Allow exact-number bets",
    description: "Enable straight-up single-number betting.",
    default: "true",
  },
  {
    key: "game.roulette.bet.oddEnabled",
    type: "BOOLEAN",
    category: "Roulette",
    label: "Allow odd bets",
    description: "Enable the odd betting option.",
    default: "true",
  },
  {
    key: "game.roulette.bet.evenEnabled",
    type: "BOOLEAN",
    category: "Roulette",
    label: "Allow even bets",
    description: "Enable the even betting option.",
    default: "true",
  },
  {
    key: "game.roulette.bet.redEnabled",
    type: "BOOLEAN",
    category: "Roulette",
    label: "Allow red bets",
    description: "Enable the red betting option.",
    default: "true",
  },
  {
    key: "game.roulette.bet.blackEnabled",
    type: "BOOLEAN",
    category: "Roulette",
    label: "Allow black bets",
    description: "Enable the black betting option.",
    default: "true",
  },
  // --- Real-time Ludo ---
  {
    key: "game.ludo.enabled",
    type: "BOOLEAN",
    category: "Ludo",
    label: "Ludo enabled",
    description: "Master feature flag for all Ludo user surfaces.",
    default: "false",
  },
  {
    key: "game.ludo.matchmakingEnabled",
    type: "BOOLEAN",
    category: "Ludo",
    label: "Matchmaking enabled",
    description: "Allow users to enter automatic matchmaking queues.",
    default: "true",
  },
  {
    key: "game.ludo.twoPlayerEnabled",
    type: "BOOLEAN",
    category: "Ludo",
    label: "Two-player mode",
    description: "Enable two-player quick matches.",
    default: "true",
  },
  {
    key: "game.ludo.threePlayerEnabled",
    type: "BOOLEAN",
    category: "Ludo",
    label: "Three-player mode",
    description: "Enable three-player matches using red, blue and yellow seats.",
    default: "true",
  },
  {
    key: "game.ludo.fourPlayerEnabled",
    type: "BOOLEAN",
    category: "Ludo",
    label: "Four-player mode",
    description: "Enable four-player classic matches.",
    default: "true",
  },
  {
    key: "game.ludo.maintenanceMode",
    type: "BOOLEAN",
    category: "Ludo",
    label: "Maintenance mode",
    description: "Keep Ludo visible but reject queue and gameplay commands.",
    default: "false",
  },
  {
    key: "game.ludo.textChatEnabled",
    type: "BOOLEAN",
    category: "Ludo",
    label: "Text chat enabled",
    description: "Allow entitled Plus and Pro members to send match text.",
    default: "true",
  },
  {
    key: "game.ludo.voiceEnabled",
    type: "BOOLEAN",
    category: "Ludo",
    label: "Voice enabled",
    description: "Allow entitled Pro members to use WebRTC voice signalling.",
    default: "false",
  },
  {
    key: "game.ludo.subscriptionPurchaseEnabled",
    type: "BOOLEAN",
    category: "Ludo",
    label: "Membership purchases enabled",
    description: "Allow new Razorpay Plus/Pro subscriptions.",
    default: "false",
  },
  {
    key: "game.ludo.turnDurationSeconds",
    type: "NUMBER",
    category: "Ludo",
    label: "Turn duration",
    description: "Authoritative seconds available for each roll or move.",
    default: "30",
    min: 10,
    max: 180,
    integer: true,
  },
  {
    key: "game.ludo.reconnectionGraceSeconds",
    type: "NUMBER",
    category: "Ludo",
    label: "Reconnect grace period",
    description: "Seconds before a disconnected player is forfeited.",
    default: "90",
    min: 15,
    max: 900,
    integer: true,
  },
  {
    key: "game.ludo.matchAcceptanceSeconds",
    type: "NUMBER",
    category: "Ludo",
    label: "Match acceptance window",
    description: "Seconds matched players have to accept and become ready.",
    default: "20",
    min: 5,
    max: 120,
    integer: true,
  },
  {
    key: "game.ludo.queueTimeoutSeconds",
    type: "NUMBER",
    category: "Ludo",
    label: "Queue timeout",
    description: "Seconds before an unmatched queue entry expires.",
    default: "120",
    min: 15,
    max: 1800,
    integer: true,
  },
  {
    key: "game.ludo.threeSixesRule",
    type: "BOOLEAN",
    category: "Ludo",
    label: "Three consecutive sixes",
    description: "End the turn without movement on a third consecutive six.",
    default: "true",
  },
  {
    key: "game.ludo.pawnsPerPlayer",
    type: "NUMBER",
    category: "Ludo",
    label: "Pawns per player",
    description: "Pawns assigned to each player; initial release defaults to four.",
    default: "4",
    min: 1,
    max: 4,
    integer: true,
  },
  {
    key: "game.ludo.extraTurnOnSix",
    type: "BOOLEAN",
    category: "Ludo",
    label: "Extra turn on six",
    description: "Grant another roll after a six unless the consecutive-six rule ends the turn.",
    default: "true",
  },
  {
    key: "game.ludo.extraTurnOnCapture",
    type: "BOOLEAN",
    category: "Ludo",
    label: "Extra turn on capture",
    description: "Grant another roll after capturing one or more opponent pawns.",
    default: "true",
  },
  {
    key: "game.ludo.inactiveForfeitTurns",
    type: "NUMBER",
    category: "Ludo",
    label: "Inactive turns before forfeit",
    description: "Consecutive server turn expirations allowed before forfeit.",
    default: "3",
    min: 1,
    max: 10,
    integer: true,
  },
  {
    key: "game.ludo.chatMaxCharacters",
    type: "NUMBER",
    category: "Ludo",
    label: "Chat character limit",
    description: "Maximum Unicode characters in one custom match message.",
    default: "160",
    min: 20,
    max: 200,
    integer: true,
  },
  {
    key: "game.ludo.chatRateLimitPer10Seconds",
    type: "NUMBER",
    category: "Ludo",
    label: "Chat burst limit",
    description: "Messages one user may send per rolling ten-second window.",
    default: "5",
    min: 1,
    max: 20,
    integer: true,
  },
  {
    key: "game.ludo.quickMessages",
    type: "STRING",
    category: "Ludo",
    label: "Free quick messages",
    description:
      "JSON string array of the fixed free-plan greetings (the server always validates codes).",
    default: '["HELLO","HI"]',
  },
  {
    key: "game.ludo.freeReactionCount",
    type: "NUMBER",
    category: "Ludo",
    label: "Free reaction count",
    description:
      "How many configured reaction codes are exposed to free users (maximum three in this release).",
    default: "3",
    min: 0,
    max: 3,
    integer: true,
  },
  {
    key: "game.ludo.minimumSupportedAppVersion",
    type: "STRING",
    category: "Ludo",
    label: "Minimum app version",
    description: "Optional semantic app version required for Ludo; blank disables the gate.",
    default: "",
  },
  {
    key: "game.ludo.plusPlanName",
    type: "STRING",
    category: "Ludo",
    label: "Plus plan name",
    description: "Display name for the ₹99/month text-chat membership.",
    default: "Ludo Plus",
  },
  {
    key: "game.ludo.proPlanName",
    type: "STRING",
    category: "Ludo",
    label: "Pro plan name",
    description: "Display name for the ₹149/month text-and-voice membership.",
    default: "Ludo Pro",
  },
  {
    key: "game.ludo.plusPlanId",
    type: "STRING",
    category: "Ludo",
    label: "PLUS Razorpay plan ID",
    description:
      "Razorpay monthly ₹99 plan ID (plan_...). If empty, the environment fallback is used.",
    default: "",
  },
  {
    key: "game.ludo.proPlanId",
    type: "STRING",
    category: "Ludo",
    label: "PRO Razorpay plan ID",
    description:
      "Razorpay monthly ₹149 plan ID (plan_...). If empty, the environment fallback is used.",
    default: "",
  },
  // --- Web (in-app web zone) ---
  {
    key: "web.baseUrl",
    type: "STRING",
    category: "Web",
    label: "Web base URL",
    description: "Base URL of the Money Marathon web experience opened in-app.",
    default: "https://moneymarathon.in/",
  },
  // --- Social ---
  {
    key: "social.telegramUrl",
    type: "STRING",
    category: "Social",
    label: "Telegram channel/group URL",
    description:
      "URL opened by the app Join Telegram card on the home screen. Leave empty to hide the card.",
    default: "",
  },
  {
    key: "social.linkedinUrl",
    type: "STRING",
    category: "Social",
    label: "LinkedIn page URL",
    description:
      "URL opened by the app Follow LinkedIn card on the home screen. Leave empty to hide the card.",
    default: "",
  },
  // --- Levels (progression is driven by lifetime coins earned) ---
  {
    key: "levels.curve",
    type: "STRING",
    category: "Levels",
    label: "Level curve",
    description:
      'JSON: {"type":"quadratic","base":100} (total lifetime coins to reach level n = base*n*n) or {"type":"table","thresholds":[100,400,900,...]} (total coins to reach level n+1).',
    default: '{"type":"quadratic","base":100}',
  },
  {
    key: "levels.ranks",
    type: "STRING",
    category: "Levels",
    label: "Rank names",
    description: "JSON array of rank names, one per 5 levels.",
    default:
      '["Bronze Scout","Silver Hunter","Gold Raider","Platinum Elite","Diamond Legend","Mythic Champion"]',
  },
] as const;

export const SETTINGS_BY_KEY: Record<string, SettingDefinition> = Object.fromEntries(
  SETTINGS_REGISTRY.map((definition) => [definition.key, definition]),
);

// ---- DTOs ----

export interface SettingDto {
  key: string;
  value: string;
  type: SettingType;
  category: string;
  label: string;
  description: string;
  isDefault: boolean;
  /** True for write-only credential fields (value is never returned). */
  secret: boolean;
  /** Whether a non-empty value is stored — lets the UI show "configured"
   *  for secrets without exposing them. */
  hasValue: boolean;
}

export const updateSettingsSchema = z.object({
  // key -> string value; validated against the registry in the service.
  values: z.record(z.string(), z.string().max(500)),
});
export type UpdateSettingsInput = z.infer<typeof updateSettingsSchema>;
